name: 构建和推送 Docker 镜像

on:
  push:
    branches:
      - main  # 只在 main 分支更新时触发
  pull_request:
    branches:
      - main  # 在 pull request 合并到 main 分支时触发
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  build:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 环境

    steps:
    - name: 检出代码
      uses: actions/checkout@v4  # 检出当前仓库的代码

    - name: 设置 Docker Buildx
      uses: docker/setup-buildx-action@v3  # 设置 Docker Buildx（用于多平台构建）

    - name: 登录 Docker Hub
      uses: docker/login-action@v3  # 登录到 Docker Hub
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}  # 从 GitHub Secrets 中获取 Docker Hub 用户名
        password: ${{ secrets.DOCKER_HUB_TOKEN }}  # 从 GitHub Secrets 中获取 Docker Hub 密码

    - name: 构建并推送 Docker 镜像
      uses: docker/build-push-action@v6  # 使用 Docker Build-Push Action
      with:
        context: .  # 设置构建上下文为当前目录
        push: true  # 启用推送功能
        tags: ${{ secrets.DOCKER_USERNAME }}/firecrawl:latest 

