name: 自动更新代码

on:
  schedule:
    - cron: '0 0 * * *'  # 每天执行一次（根据需要调整频率）
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  update:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 环境
    steps:
    - name: 检出当前仓库
      uses: actions/checkout@v4  # 使用 GitHub Actions 的检出功能

    - name: 拉取源仓库的最新代码
      run: |
        git remote add upstream https://github.com/mendableai/firecrawl.git  # 添加源仓库
        git fetch upstream  # 拉取源仓库的更新
        git checkout main  # 切换到 main 分支
        git merge upstream/main --no-commit --no-ff  # 合并源仓库的更新，但不提交

        # 删除更新中带来的工作流文件变动（即 .github/workflows 目录）
        git restore --staged .github/workflows  # 恢复暂存区的工作流文件变动
        git checkout .github/workflows  # 恢复工作区的工作流文件变动

        git commit -m "更新源代码，但不包括工作流文件"  # 提交更新（不包括工作流文件）
        git push origin main  # 将更新推送到自己的仓库
