name: 自动更新代码

on:
  schedule:
    - cron: '0 0 * * *'  # 每小时执行一次，调整为你想要的频率
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  update:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 环境
    steps:
    - name: 检出当前仓库
      uses: actions/checkout@v4  # 使用 GitHub Actions 的检出功能

    - name: 拉取源仓库的最新代码
      run: |
        git remote add upstream https://github.com/mendableai/firecrawl.git  # 添加源仓库
        git fetch upstream  # 拉取源仓库的更新
        git checkout main  # 切换到 main 分支
        git merge upstream/main  # 将源仓库的更新合并到本地仓库
        git push origin main  # 将合并后的更新推送到自己的仓库
